---
# Some common variables used in more then one roles
 
nextcloud_base_dir:            /opt/nextcloud
nextcloud_credential_store:    "{{ nextcloud_base_dir }}/secrets"
nextcloud_data_dir:            "{{ nextcloud_base_dir }}/data"
nextcloud_www_dir:             "{{ nextcloud_base_dir }}/www"
nextcloud_config_dir:          "{{ nextcloud_base_dir }}/config"
nextcloud_database_dir:        "{{ nextcloud_base_dir }}/database"

traefik_config_dir:            "{{ nextcloud_base_dir }}/traefik"

portainer_data_dir:            "{{ nextcloud_base_dir }}/portainer-data"

nextcloud_container_data_dir:  /var/nc-data

docker_postgres_image:         10-alpine
docker_mysql_image:            latest
docker_nextcloud_image:        fpm-alpine
docker_nginx_image:            alpine
docker_adminer_image:          latest
docker_traefik_image:          alpine
docker_watchtower_image:       latest
docker_redis_image:            4-alpine

# nginx resolver http://blog.zorinaq.com/nginx-resolver-vulns/)
nginx_resolver              = '127.0.0.1 valid=30s'
